### ISSUE TITLE
Typo in 4.1

### ISSUE THREAD

**Issue by Vozf** [Yorko/mlcourse.ai#350]
https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/topic04_linear_models/topic4_linear_models_part1_mse_likelihood_bias_variance.ipynb
k should be renamed to x.
![image](https://user-images.githubusercontent.com/22998537/45756573-dfd8ab80-bc29-11e8-9412-249940eb0a35.png)
P.S. Maybe you should change the '|' notation. It got me confused because I thoutght that it is conditional probability and had to search for additional information
P.S.S Also for some reason the maximum likelihood method is not finished and resulting theta is not found after finding the derivative

**Comment by Yorko** [comment]
Thanks, fixed the first typo.

As for rendering, you shouldn't trust GitHub, it doesn't render Jupyter notebooks correctly. With nbviewer, [this notebook](http://nbviewer.jupyter.org/github/Yorko/mlcourse.ai/blob/master/jupyter_english/topic04_linear_models/topic4_linear_models_part1_mse_likelihood_bias_variance.ipynb) looks fine. 

Agreed! It's better to use semicolon to separate arguments and parameters. Changed it. Thanks!
