### ISSUE TITLE
Topic 6

### ISSUE THREAD

**Issue by Vozf** [Yorko/mlcourse.ai#351]
In kaggle kernel In [38] it is said that the performance got worse when it actually got better.
https://www.kaggle.com/kashnitsky/topic-6-feature-engineering-and-feature-selection
In habr article however the numbers have really gotten worse.

Also in assignment 6 "Train a LASSO model " it is not said whether I should train on scaled X or original X. As I understand it should be scaled X to perform next task on finding least important features

**Comment by Yorko** [comment]
Fixed in 93bff3d10627973d16b57bbe10b97952282b4815 and on Kaggle as well
