### ISSUE TITLE
Topic 7 typo

### ISSUE THREAD

**Issue by Vozf** [Yorko/mlcourse.ai#352]
Agglomerative clustering
`# linkage — is an implementation if agglomerative algorithm`
should be `of` instead of `if`

Assignment 7
`For classification, use the support vector machine – class sklearn.svm.LinearSVC. In this course, we did study this algorithm separately, but it is well-known and you can read about it, for example here.`
it seems that it shoud be `didn't` instead of `did`.

**Comment by Yorko** [comment]
Fixed that, thanks!
