### ISSUE TITLE
Assignment 9

### ISSUE THREAD

**Issue by Vozf** [Yorko/mlcourse.ai#355]
https://www.kaggle.com/kashnitsky/assignment-9-time-series-analysis
1) web form is not corresponding to the questions in the task. At least 1st question is missing

2) I doubt that in the 1st question there is a correct answer. Simple operations lead to result 3426.195682 which is not listed in the possible answers. Kernel related. In q2-4 the situation is the same. Practically no coding, but copypasting from the lecture. Still not the results listed in the possible answers. Although may be I didn't understand the tasks correctly
[kernel (2).zip](https://github.com/Yorko/mlcourse.ai/files/2411140/kernel.2.zip)

3) For some reason numpy is not imported when it is definetly needed

**Comment by Yorko** [comment]
Fixed in d9b836f95ccb2c770a5f3d5d426ea8f0a46d7b80 and 846501b68e933ca6dab23654cf23bd9e8840d6f5
