### ISSUE TITLE
Add athlete_events.csv to data folder

### ISSUE THREAD

**Issue by morcmarc** [Yorko/mlcourse.ai#358]
The athlete_events.csv file seems to be missing from the data folder. Sure, it can be downloaded via the [Kaggle link][0] but it's not immediately obvious.

[0]: https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results/version/2

**Comment by Yorko** [comment]
Too big for GitHub => download from Kaggle
