### ISSUE TITLE
Docker image - seaborn

### ISSUE THREAD

**Issue by priteshwatch** [Yorko/mlcourse.ai#362]
Looks like the docker image is not connected to seaborn 0.9.0 , your exercise 2 requires catplot .

**Comment by Yorko** [comment]
There's a special checker for Docker image - `check_docker.ipynb`. Seaborn  0.8.1 works fine, [nbviewer](http://nbviewer.jupyter.org/github/Yorko/mlcourse.ai/blob/master/docker_files/check_docker.ipynb). 

I'm closing the issue. You can reopen if only you specify correctly, where and how the error occurred.
[How to effectively report bugs on GitHub](https://coenjacobs.me/2013/12/06/effective-bug-reports-on-github/)

**Comment by Yorko** [comment]
Created a new [image](https://hub.docker.com/r/festline/mlcourse_ai/), you can stick to previous instructions, just run `python run_docker_jupyter.py`
