### ISSUE TITLE
Topic 3, Some graphviz images missing

### ISSUE THREAD

**Issue by prickly-u** [Yorko/mlcourse.ai#376]
It looks like graphviz images after code cell 9 and 13 were not rendered. Considering presence of the graph after the 6th cell, it isn't a browser error and there should not be many difficulties restoring them.

**Comment by Yorko** [comment]
Source you're referring to?

**Comment by Yorko** [comment]
Thanks, fixed in 5aa7bed998ee32fb3128faf7491e527f1d89f1c7
