### ISSUE TITLE
Variance formula in Article 3 and Assignment 3

### ISSUE THREAD

**Issue by prickly-u** [Yorko/mlcourse.ai#377]
The formulas for variance D in Article 3 and Assignment 3 are somewhat different, and both seem not ideal. In the article index _i_ is used for both inner and external sums of _y_, that may be not quite right from a formal point of view. Possibly, in the assigment it was corrected by using _yj_ and _xj,_ however, _j_ and _xj_ was used in the same paragraph to mark the split feature. That can mislead someone.

**Comment by Yorko** [comment]
Agree with the first one. For the second one, _j_ is just an index, _xj_ stands for feature number _j_. But then there's a problem with a formula for D(X) where it's not clear, what _xi_ in X means. I'll fix that later.

**Comment by Yorko** [comment]
Done. 585185ef0c861bcf9d565a0064f3d1197715c371
