### ISSUE TITLE
Topic 3. Decision tree regressor, MSE

### ISSUE THREAD

**Issue by lalimpiev** [Yorko/mlcourse.ai#382]
В примере по DecisionTreeRegressor неправильный расчет MSE в названии графика:
`plt.title("Decision tree regressor, MSE = %.2f" % np.sum((y_test - reg_tree_pred) ** 2))`
Нужно ещё поделить на количество наблюдений, предлагаю поправить так:
`plt.title("Decision tree regressor, MSE = %.4f" % (np.sum((y_test - reg_tree_pred) ** 2) / n_test))`

Файл:
https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/topic03_decision_trees_kNN/topic3_decision_trees_kNN.ipynb
И в русской версии аналогично:
https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_russian/topic03_decision_trees_knn/topic3_trees_knn.ipynb

**Comment by Yorko** [comment]
Thanks, fixed
