### ISSUE TITLE
Topic 2: wrong direction on chart in section 4.3 t-SNE

### ISSUE THREAD

**Issue by ptaiga** [Yorko/mlcourse.ai#394]
![1_1](https://user-images.githubusercontent.com/1929262/47232325-0e3bd900-d3d8-11e8-9e12-8193c4a917ed.jpg)

Wrong direction on chart for the article on Github (https://mlcourse.ai/notebooks/blob/master/jupyter_english/topic02_visual_data_analysis/topic2_visual_data_analysis.ipynb):  "__south-west__". 
But it's true for the article on Medium (https://medium.com/open-machine-learning-course/open-machine-learning-course-topic-2-visual-data-analysis-in-python-846b989675cd), as there is another version of the chart:

![2_1](https://user-images.githubusercontent.com/1929262/47232361-23b10300-d3d8-11e8-96b0-065aeb7a9cc8.jpg)

It's not a critical inaccuracy, but a little embarrassing.

**Comment by Yorko** [comment]
Thanks, fixed in 74cd73f714f6f27604b0a7175e06205dd6b76610
