### ISSUE TITLE
Typo in 4.1

### ISSUE THREAD

**Issue by kazimanil** [Yorko/mlcourse.ai#396]
After defining linearity of weights there is a mathematical expression which can not be displayed clearly due to a typo I believe. Presumably *∀k* is meant.
Best

> where $\forall\ k\ $,

**Comment by Yorko** [comment]
Source?

[Here](https://mlcourse.ai/notebooks/blob/master/jupyter_english/topic04_linear_models/topic4_linear_models_part1_mse_likelihood_bias_variance.ipynb?flush_cache=true) it's OK.

**Comment by kazimanil** [comment]
I was using GitHub page rather than NBViewer.

[Here](https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/topic04_linear_models/topic4_linear_models_part1_mse_likelihood_bias_variance.ipynb) it seems troubled. I guess the problem is with using GitHub rather then NBViewer?

**Comment by Yorko** [comment]
Yes, notebooks are correctly rendered only with nbviewer
