### ISSUE TITLE
Topic 4. Part 4: Some modules are imported at the beginning, but are not used further in the text

### ISSUE THREAD

**Issue by ptaiga** [Yorko/mlcourse.ai#406]
![2018-11-05 23-42-56 jupyter notebook viewer - google chrome](https://user-images.githubusercontent.com/1929262/48025917-b7fbc380-e155-11e8-95e2-2666ea50c833.jpg)

It seems that _TfidfTransformer, TfidfVectorizer, LinearSVC_ were forgotten to be removed when preparing the final [article](https://mlcourse.ai/notebooks/blob/master/jupyter_english/topic04_linear_models/topic4_linear_models_part4_good_bad_logit_movie_reviews_XOR.ipynb). If they are left on purpose, it seems that it is worth adding a few words about them in the text.

**Comment by Yorko** [comment]
Thanks, fixed in 29d7e25f66fddf669792b9c768951f07b8280228
