### ISSUE TITLE
Topic 3: Some tree schemes are not rendered

### ISSUE THREAD

**Issue by ptaiga** [Yorko/mlcourse.ai#407]
![2018-11-06 00-10-39 jupyter notebook viewer - google chrome](https://user-images.githubusercontent.com/1929262/48027182-1e361580-e159-11e8-99c1-3673d7150172.jpg)

The following cells do not render the tree scheme in the [article](https://mlcourse.ai/notebooks/blob/master/jupyter_english/topic03_decision_trees_kNN/topic3_decision_trees_kNN.ipynb): **In[9], In[13], In[24], In[32]**. Checked in Chrome and Firefox.

There is a similar [closed issue](https://github.com/Yorko/mlcourse.ai/issues/376), but the problem remained.

**Comment by Yorko** [comment]
Thanks, fixed in 29d7e25f66fddf669792b9c768951f07b8280228

**Comment by Yorko** [comment]
Not fixed actually :)

**Comment by Yorko** [comment]
fixed in 8cb2ee0f393e57cef55827fb8f3ff18c82534330
