### ISSUE TITLE
Topic 2.2: For new versions, add sns.set() to apply styles throughout notebook

### ISSUE THREAD

**Issue by ptaiga** [Yorko/mlcourse.ai#408]
![2018-10-26 16-00-58 jupyter notebook viewer - google chrome](https://user-images.githubusercontent.com/1929262/48028382-630f7b80-e15c-11e8-9787-71c6a6100135.jpg)

In the [article](https://mlcourse.ai/notebooks/blob/master/jupyter_english/topic02_visual_data_analysis/topic2_additional_seaborn_matplotlib_plotly.ipynb):
> Even by simply adding import seaborn in your code, the images of your plots will become much nicer.

This is correct for older versions of seaborn.
For new versions, add `sns.set()` to apply styles throughout notebook.

From the [documentation](https://seaborn.pydata.org/tutorial/aesthetics.html):
> (Note that in versions of seaborn prior to 0.8, set() was called on import. On later versions, it must be explicitly invoked).

**Comment by Yorko** [comment]
Thanks, fixed in d404c66267bfa1af06088d2a58455bccebdb23ce
