### ISSUE TITLE
Topic 5 Part 1: KDE Plot used for 'Customer service calls'

### ISSUE THREAD

**Issue by ddonetskov** [Yorko/mlcourse.ai#412]
The KDE plot is used for 'Customer service calls' in Topic 5 Part 1. Due to the nature of KDE the plot is smoother than it needs to be for this type of discrete data e.g. the pikes for the loyal customers are lowered and there is the tail of the negative numbers of phone calls for the churned customers.

I suggest correcting to probably distplot which can estimate the distribution with both the histogram and the kernel. An example of code is shown below.

```
import pandas as pd

from matplotlib import pyplot as plt
import seaborn as sns

plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = 10, 6

telecom_data = pd.read_csv('../../data/telecom_churn.csv')

ax = sns.distplot(telecom_data[telecom_data['Churn'] == False]['Customer service calls'], label = 'Loyal')
ax = sns.distplot(telecom_data[telecom_data['Churn'] == True]['Customer service calls'],  label = 'Churn')        
ax.set(xlabel='Number of calls', ylabel='Density')
ax.legend()
plt.show()
```

![image](https://user-images.githubusercontent.com/19440485/48181150-6e6ace80-e337-11e8-8ba7-e1b14ff144c4.png)

**Comment by Yorko** [comment]
thanks, decided just to replace with histograms. e08d99f3cc8fb0cce3886c00e2c1bd4990609430
