### ISSUE TITLE
Topic 6: "Lasso and Ridge regressions" isn't on the main page 

### ISSUE THREAD

**Issue by ptaiga** [Yorko/mlcourse.ai#419]
Link to [Topic 6: "Lasso and Ridge regressions"](https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/topic06_features_regression/lesson6_lasso_ridge.ipynb) isn't on the main page

**Comment by Yorko** [comment]
It's not intended to be

**Comment by ptaiga** [comment]
Thanks for the answer!
I want to clarify: does it make sense in such Issues? For example, a piece
of russian text in the english lesson 7:
https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/topic07_unsupervised/lesson7_part1_PCA.ipynb
.

чт, 22 нояб. 2018 г. в 13:07, Yury Kashnitskiy <notifications@github.com>:

**Comment by Yorko** [comment]
Yes, it makes sense. You can open an issue if you see smth like this.
