### ISSUE TITLE
A1 (demo). Pandas and UCI adult dataset - small error

### ISSUE THREAD

**Issue by polezhaev-ds** [Yorko/mlcourse.ai#567]
Small error in
[https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/assignments_demo/assignment01_pandas_uci_adult_solution.ipynb](https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/assignments_demo/assignment01_pandas_uci_adult_solution.ipynb)
> . Among whom the proportion of those who earn a lot(>50K) is more: among married or single men (marital-status feature)? Consider married those who have a marital-status starting with Married (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.

One of the steps of the proposed solution is
`data[(data['sex'] == 'Male') &
     (data['marital-status'].isin(['Never-married', 
                                   'Separated', 'Divorced']))]['salary'].value_counts()`

Why  don't you consider adults with **marital-status == 'Widowed'**? So, the correct step is the following:
`data[(data['sex'] == 'Male') &
     (data['marital-status'].isin(['Never-married', 
                                   'Separated', 'Divorced', 'Widowed']))]['salary'].value_counts()`

**Comment by Yorko** [comment]
Thanks, fixed in 9260dc467d3f6c835ff3485e4e5bd4a4908a7f83

**Comment by avm19** [comment]
This correction is not reflected in 
https://mlcourse.ai/book/topic01/assignment01_pandas_uci_adult_solution.html

**Comment by Yorko** [comment]
Thanks, @avm19! Fixed in #700
