### ISSUE TITLE
A2 demo: incomplete information in answers form

### ISSUE THREAD

**Issue by andresti** [Yorko/mlcourse.ai#571]
The answers form asks: "What's the rounded difference between median values of age for smokers and non-smokers? You'll need to figure out the units of feature age in this dataset."
This formulation should be answered with years, logically taken. But turns out that it wants months instead, so that should be mentioned.

**Comment by Yorko** [comment]
No, that's correct. You need to figure out the unit by yourself, and then convert the difference into months.

**Comment by andresti** [comment]
I meant that the text of the question does not say that it should be converted into months.

**Comment by Yorko** [comment]
That was correctly stated in the A2 notebook. Copied the same question formulation to the [web-form](https://docs.google.com/forms/d/13cE_tSIb6hsScQvvWUJeu1MEHE5L6vnxQUbDYpXsf24)
