### ISSUE TITLE
Re-run topic9_part1_time_series_python.ipynb for English version

### ISSUE THREAD

**Issue by khof312** [Yorko/mlcourse.ai#573]
Plots and output are missing for the second half of the notebook when viewed via nbviewer:
https://nbviewer.jupyter.org/github/Yorko/mlcourse_open/blob/master/jupyter_english/topic09_time_series/topic9_part1_time_series_python.ipynb

Globally, an excellent resource. Thanks!

**Comment by Yorko** [comment]
Thanks! Fixed in bce17595470bd6f93f84799c4f35a6444c35f476
