### ISSUE TITLE
Assignment 4 fix is not published

### ISSUE THREAD

**Issue by chekan-o** [Yorko/mlcourse.ai#584]
There was a fix made at https://github.com/Yorko/mlcourse.ai/commit/e5227683e961d0a3327d0dca3b76964858b26098 but it was not merged to /jupyter_english/assignments_spring2019/assignment4_time_series.ipynb

**Comment by Yorko** [comment]
Thanks, fixed in 5dcb364b6802c35dafe19f6f1d8e07b644e12133
