### ISSUE TITLE
Issue with filling NAN values in the demo assignment 3

### ISSUE THREAD

**Issue by Shakarim94** [Yorko/mlcourse.ai#590]
In assignment03_decision_trees.ipynb and its solution, there is this piece of code:

for c in categorical_columns:
    data_train[c].fillna(data_train[c].mode(), inplace=True)
    data_test[c].fillna(data_train[c].mode(), inplace=True)

This code is supposed to replace the NAN values with the mode of the corresponding categorical column. However, it does nothing. I suspect it is because the .mode() function returns a Dataframe object instead of a single value. So I fixed it by replacing .mode() by .mode()[0]. Can you push this fix to the demo assignments 3 and its solution?

**Comment by Yorko** [comment]
Thanks, fixed in b543e598f2546f30446d08aabd2645c901896b09

**Comment by Yorko** [comment]
When Kaggle Kernels are up'n'running again (:harold:) - will fix in Kernels as well
