### ISSUE TITLE
Issue with a simple typo

### ISSUE THREAD

**Issue by Arnab9Codes** [Yorko/mlcourse.ai#592]
in mlcourse.ai/jupyter_english/topic02_visual_data_analysis/topic2_additional_seaborn_matplotlib_plotly.ipynb

there is a typo in Article Outline:
In the end of 2nd point there is a extra parentheses.

Article outline
1.Dataset
2.DataFrame.plot())
3.Seaborn
4.Plotly
5.Demo assignment
6.Useful resources

**Comment by Yorko** [comment]
Thanks, fixed in 2f843ac87b942a01149459ff220df1e0ee27e31e
