### ISSUE TITLE
Times series 

### ISSUE THREAD

**Issue by Rym96** [Yorko/mlcourse.ai#595]
Getting this error "ZeroDivisionError:` float division by zero" whenever I want to run this code
Can't seem to explain why this is happening
```
%%time
data =df.pourcentage[:-20] # leave some data for testing

# initializing model parameters alpha, beta and gamma
x = [0, 0, 0] 

# Minimizing the loss function 
opt = minimize(timeseriesCVscore, x0=x, 
               args=(data, mean_squared_log_error), 
               method="TNC", bounds = ((0, 1), (0, 1), (0, 1))
              )

# Take optimal values...
alpha_final, beta_final, gamma_final = opt.x
print(alpha_final, beta_final, gamma_final)

# ...and train the model with them, forecasting for the next 50 hours
model = HoltWinters(data, slen = 24, 
                    alpha = alpha_final, 
                    beta = beta_final, 
                    gamma = gamma_final, 
                    n_preds = 50, scaling_factor = 3)
model.triple_exponential_smoothing()

```

**Comment by Yorko** [comment]
Sorry for not addressing this issue, now I'm back preparing for the last mlcourse.ai session.

Do you get the same error running the code in our Docker container?

**Comment by Yorko** [comment]
Or can you at least provide error stack trace to see which line actually causes zero division?

**Comment by Yorko** [comment]
Re-run the code with our provided Docker image. The mentioned error is not reproduced. Closing now considering that instructions to reproduce the error are not provided.
