### ISSUE TITLE
links are broken on mlcourse.ai

### ISSUE THREAD

**Issue by nickcorona** [Yorko/mlcourse.ai#596]
example: https://festline.github.io/notebooks/blob/master/jupyter_english/topic02_visual_data_analysis/topic2_visual_data_analysis.ipynb?flush_cache=true

**Comment by Yorko** [comment]
Thanks, it's a known issue, the fix is in progress

**Comment by nickcorona** [comment]
Issue's still happening.

**Comment by Yorko** [comment]
Right, let the issue be open untill it's fixed. Added a precaution on the main page, that links are temporarily not working

**Comment by Yorko** [comment]
Fixed.
