### ISSUE TITLE
Images are not displayed

### ISSUE THREAD

**Issue by valware** [Yorko/mlcourse.ai#598]
Some images in the jupyter notebooks are not displayed even when put in the html tags, why is this happening?
example: <img src="../../img/pandas.jpg" width=50% /> in Topic 1 and <img src='https://habrastorage.org/web/b2b/029/d89/b2b029d898f64bbbb158e15d29595969.png' width=70%> in Topic 10.

**Comment by Yorko** [comment]
Here it's OK https://mlcourse.ai/articles/topic1-exploratory-data-analysis-with-pandas/

With nbviewer as well. Do you use nbviewer to explore notebook content?
