### ISSUE TITLE
Правильный ответ задания topic1_habr_pandas.ipynb

### ISSUE THREAD

**Issue by sergei-from-vironit** [Yorko/mlcourse.ai#604]
Добрый день.

Пробую выполнить заданее которое вы размещали на хабр. Не могу получить конечный ответ такой же как у вас. Все промежуточные вычисления совпадают, но только не конечнай операция  pd.crosstab(df['Many_service_calls'] & df['International plan'] , df['Churn']) 
Подскажите пожалуйста, что можно сделать или поменять?
http://prntscr.com/owufg2

**Comment by Yorko** [comment]
Добрый день!

Для вопросов по материалам курса используйте Slack [OpenDataScience](https://ods.ai/), каналы #mlcourse_ai или #mlcourse_ai_rus
