### ISSUE TITLE
2019 Fall - A1 Q3

### ISSUE THREAD

**Issue by sgdread** [Yorko/mlcourse.ai#606]
[A1](https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/assignments_fall2019/assignment1_pandas_olympic.ipynb) Q3 seems doesn't have a correct answer.
The options provided in the form/notebook has an option for mean/std with duplicates: (171.8, 6.5). However, I don't think it is a good idea to keep duplicates in this specific question. If you drop duplicates, then the answer is (171.8, 6.6), which is not available in options.

**Comment by Yorko** [comment]
Thanks, but this shall be discussed in a specified thread in Slack -the one mentioned in the assignment
