### ISSUE TITLE
all of the links jqr.com 🇨🇳 is 404

### ISSUE THREAD

**Issue by jy1989** [Yorko/mlcourse.ai#607]

**Comment by Yorko** [comment]
Maybe the site is temporarily down - dunno, will leave the issue open for now

**Comment by bbbooo313** [comment]
[oubomenhu.com](oubomenhu.com)  老哥换个友链吗？
联系QQ：1297532431

**Comment by Yorko** [comment]
Fixed in d27324127184a03fb8b9709bc8ff07b860499bca
