### ISSUE TITLE
Potentially incorrect statement about .map vs .replace in topic1_pandas_data_analysis.ipynb

### ISSUE THREAD

**Issue by andrei-khveras** [Yorko/mlcourse.ai#608]
In **Applying Functions to Cells, Columns and Rows** section of topic1_pandas_data_analysis.ipynb exercise when explaining how to replace values in column it is stated that `.replace` does the same thing as `.map` that, I think, is just partially correct.
While `.map` is applied to the dataframe produces NaN values for keys not found in the map, `.replace` updates values matching keys in the map only.

**Comment by bbbooo313** [comment]
[dapingtai3344.com](dapingtai3344.com)  老哥换个友链吗？
联系QQ：1297532431

**Comment by Yorko** [comment]
Thanks, true! Addressed the issue here 506acee3a970a02607cde4be223c16c60fb8bf64
