### ISSUE TITLE
The link - https://mlcourse.ai/video - gives a 404 error.

### ISSUE THREAD

**Issue by vidyabhandary** [Yorko/mlcourse.ai#609]
In 'Fall 2019. Quiz 1. Decision trees and Random Forests' assignment - at the link - 

https://nbviewer.jupyter.org/github/Yorko/mlcourse.ai/blob/master/jupyter_english/quizzes_fall2019/quiz1_trees_forests.ipynb?flush_cache=true

the link 'https://mlcourse.ai/video'

which is part of the sentence - 'There are 5 video lectures on trees, forests and their applications: mlcourse.ai/video'
gives **404 error**.

**Comment by Yorko** [comment]
Already fixed the source notebook :) nbviewer shall pick up changes later
