### ISSUE TITLE
Q1.4 from assignment02_analyzing_cardiovascular_desease_data differs in notebook and webform

### ISSUE THREAD

**Issue by nkrot** [Yorko/mlcourse.ai#616]
The formulation differs between notebook and the web form.

notebook: ` **Question 1.4. (1 point). What is the difference between median values of age for smokers and non-smokers (in months, rounded)? You'll need to figure out the units of feature `age` in this dataset.** `

in the web form : `4. What's the rounded difference between median values of age for smokers and non-smokers? You'll need to figure out the units of feature age in this dataset.`

1. The formulation in the notebook is unclear w.r.t. to what values need to be rounded, ages or difference of age value. The formulation given in the web form is better in this respect.

2. Strictly speaking, smokers live less, therefore the answer to this question is negative.

**Comment by Yorko** [comment]
Thanks! Fixed in bee151ec936756d433a7040b0ce58a3f9f4bbbb2
