### ISSUE TITLE
A3 Demo - Part 2 - Misleading output requirement in best_feature_to_split

### ISSUE THREAD

**Issue by HooZz** [Yorko/mlcourse.ai#621]
In [A3 Demo](https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/assignments_demo/assignment03_decision_trees_solution.ipynb) description of the function best_feature_to_split in Part 2 requires us to output information gain when splitting on best feature, which is supposed to be a single number, while in the demo solution this function outputs an array of information gains when splitting on all available features.

**Comment by Yorko** [comment]
Thanks! I'm not going to change the solution (tree building algorithm), so I changed the specification of the function to be implemented. Anyway, implementing a decision tree is an optional part in this assignment. 

fa3a7eba231fe2a72bb77f7c888da8598f9033b0
