### ISSUE TITLE
A2 demo - strict inequalities in problem statement but >= and <= in solution

### ISSUE THREAD

**Issue by flinge** [Yorko/mlcourse.ai#624]
question 1.7:  
>height is strictly less than 2.5%-percentile   

[https://en.wikipedia.org/wiki/Inequality_(mathematics)](https://en.wikipedia.org/wiki/Inequality_(mathematics))

**Comment by Yorko** [comment]
The solution was correct - `filtered_df` was that 90% of data that we didn't throw away, that's way inverted signs. 
But still I've committed a change to state the solution clearly f3e5b5cf88a0ab6d2b631d4858560aa51f73db5b

```
df_to_remove = df[(df['ap_lo'] > df['ap_hi']) | 
                 (df['height'] < df['height'].quantile(0.025)) |
                 (df['height'] > df['height'].quantile(0.975)) |
                 (df['weight'] < df['weight'].quantile(0.025)) | 
                 (df['weight'] > df['weight'].quantile(0.975))]
filtered_df = df[~df.index.isin(df_to_remove)]
```
