### ISSUE TITLE
Mistake in assignment 8

### ISSUE THREAD

**Issue by Ecclesiast** [Yorko/mlcourse.ai#640]
There is no true formula for updating weights using gradient descent:

![image](https://user-images.githubusercontent.com/24414958/67902793-af747800-fb72-11e9-912a-d9414ac6c020.png)

Right formula is:

![image](https://user-images.githubusercontent.com/24414958/67902989-227dee80-fb73-11e9-8cf4-c49794f45587.png)

Minus in sigma's argument is critical.

**Comment by Yorko** [comment]
Looks familiar, thanks! version control :)

Fixed in ea1fb2fe070f9c77932b5a74f09dfd34abb3c9b7

You are totally right - this is a crucial minus sign.
