### ISSUE TITLE
Docker image Kernel error

### ISSUE THREAD

**Issue by elgator** [Yorko/mlcourse.ai#641]
Windows 10
Jupyter starts, although it throws 'Kernel error' and cannot start python kernel.
[...]
File "/opt/conda/lib/python3.6/site-packages/jupyter_core/paths.py", line 412, in secure_write
    .format(file=fname, permissions=os.stat(fname).st_mode))
RuntimeError: Permissions assignment failed for secure file: '/notebooks/home/.local/share/jupyter/runtime/kernel-289a0297-fc62-4f53-bbe5-daaccaa23f33.json'.Got '33261' instead of '600'

**Comment by theptyza** [comment]
Also running docker image on Windows 10. Had the same error.
Setting `JUPYTER_RUNTIME_DIR` and `JUPYTER_DATA_DIR` in the docker start command as suggested in https://github.com/jupyter/notebook/issues/4998 fixed it for me. See https://github.com/theptyza/mlcourse.ai/commit/9f0cae3b66f3bec04d1a50bc3bce7125fea4eb46

**Comment by Yorko** [comment]
This works, thanks!
