### ISSUE TITLE
can you help find email for Измайлов Константин 

### ISSUE THREAD

**Issue by Sandy4321** [Yorko/mlcourse.ai#649]
I see
Измайлов Константин Константинович (@Izmajlovkonstantin)

can you help find email for Измайлов Константин 
I try to get him , ask code for 
https://sphere.mail.ru/curriculum/program/discipline/818/
especially for video
https://www.youtube.com/watch?v=fit-ZAWexZ0&list=PLrCZzMib1e9p6lpNv-yt6uvHGyBxQncEh&index=8

11. Введение в SQL. Курс "ВВЕДЕНИЕ В АНАЛИЗ ДАННЫХ" | Технострим

  from 

mlcourse.ai/jupyter_russian/tutorials/boruta_tutorial_Izmajlovkonstantin.ipynb

{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<center>\n",
    "<img src=\"../../img/ods_stickers.jpg\">\n",
    "## Открытый курс по машинному обучению\n",
    "<center>Автор материала: Измайлов Константин Константинович (@Izmajlovkonstantin)."
   ]
  }

**Comment by Yorko** [comment]
Man, this is not an issue, do not spam please
