### ISSUE TITLE
mlcourse.ai is down

### ISSUE THREAD

**Issue by vitvakatu** [Yorko/mlcourse.ai#654]
Hello, is https://mlcourse.ai down?

**Comment by Yorko** [comment]
Yes, looks like a GitHub pages issue. Because mlcourse.ai is just a redirection from https://festline.github.io/ which also wouldn’t work properly

**Comment by Yorko** [comment]
Just checked - it’s working :) idk 😐

**Comment by vitvakatu** [comment]
Yes, it looks like it is up again. https://downforeveryoneorjustme.com showed me that it was down.
