### ISSUE TITLE
Issue related to Lasso and Ridge regression notebook  file - mlcourse.ai/jupyter_english/topic06_features_regression/lesson6_lasso_ridge.ipynb / 

### ISSUE THREAD

**Issue by cohy** [Yorko/mlcourse.ai#659]
While plotting  Ridge coefficient vs weights, the alphas used are different from Ridge_alphas. And while fitting the the model and calculating the ridge_cv.alpha_ we're using ridge_alphas. So,in below code its taking alpha values from alpha defined for **Lasso**. if we plot using ridge alphas plot is quite different. Please suggest if this is correct plot.

n_alphas=200
ridge_alphas=np.logspace(-2,6,n_alphas)

coefs = []
for a in alphas:    # alphas = np.linspace(0.1,10,200) it's from Lasso
    model.set_params(alpha=a)
    model.fit(X, y)
    coefs.append(model.coef_)

**Comment by Yorko** [comment]
Thanks, fixed in b0a35e3584fc5c47cbc241adca43db2f76469612
