### ISSUE TITLE
jupyter_russian/project_alice/week2_analysis_hypotheses.ipynb Специализация Курсеры

### ISSUE THREAD

**Issue by eye-shield-77** [Yorko/mlcourse.ai#664]
На курсере отличается первый вопрос от указанного в файле. Вместо количества уникальных длин новых разреженных матриц там спрашивается:

Вопрос 1. Каковы длины (число сессий) новых 16 разреженных матриц?

Эти длины нужно вывести в файл через пробел. Проверить можно здесь:
https://www.coursera.org/learn/data-analysis-project/programming/lWVOk/podghotovka-i-piervichnyi-analiz-dannykh/submission

Также можно добавить во втором вопросе, что грейдер в качестве ответов "да/нет" принимает только "YES/NO", регистр важен.

**Comment by Yorko** [comment]
Спасибо за замечание! Но русская версия mlcourse.ai, включая проект Alice, больше не поддерживается. А если вопрос по специализации Яндекса и МФТИ, то это к ним на форум Coursera.
