### ISSUE TITLE
Misleading hyperlink on https://mlcourse.ai/roadmap

### ISSUE THREAD

**Issue by www050** [Yorko/mlcourse.ai#666]
Misleading hyperlink on https://mlcourse.ai/roadmap
Chapter: "Week 5. Bagging and Random Forest"
Link: “Random Forest”
Actual link:     https://mlcourse.ai/articles/topic5-part1-bagging/
Expected link: https://mlcourse.ai/articles/topic5-part2-rf/

**Comment by Yorko** [comment]
Thanks! Fixed.
