### ISSUE TITLE
do you have similar code like lesson10_part9_imbalance.ipynb  but for lightGBM

### ISSUE THREAD

**Issue by Sandy4321** [Yorko/mlcourse.ai#669]
do you have similar code like lesson10_part9_imbalance.ipynb  but for lightGBM
https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_russian/topic10_boosting/lesson10_part9_imbalance.ipynb

or catboost
to understand what is better?

**Comment by Yorko** [comment]
No, but you can adapt it for LightGBM or CatBoost for yourself, that would be a good practice.
