### ISSUE TITLE
There are no links to the datasets in a Dask tutorial

### ISSUE THREAD

**Issue by alexkataev** [Yorko/mlcourse.ai#676]
@iknyazeva
There are no links to the datasets in this Dask tutorial:
https://github.com/Yorko/mlcourse.ai/blob/master/jupyter_english/tutorials/dask_objects_and_little_dask_ml_tutorial_iknyazeva.ipynb

**Comment by Yorko** [comment]
Hi @alexkataev, not sure that Irina's gonna see this. 

the `athlete_events.csv` file is found [here on Kaggle](https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results). As for Kaggle medium, i guess it's from one of the competitions held by me during the course, but hard to say from which one precisely (there were several competitions with more or less the same idea). Maybe from [this one](https://www.kaggle.com/c/how-good-is-your-medium-article).
