### ISSUE TITLE
No demo assignment in topic-3

### ISSUE THREAD

**Issue by aulasau** [Yorko/mlcourse.ai#711]
[jupyter_english/topic03_decision_trees_kNN](https://github.com/Yorko/mlcourse.ai/tree/main/jupyter_english/topic03_decision_trees_kNN) and [jupyter_french/topic03_decision_trees_kNN](https://github.com/Yorko/mlcourse.ai/tree/main/jupyter_french/topic03_decision_trees_kNN) has no .ipynb files for the demo assignment and solution to it. 
Can you add them to the repo?

**Comment by Yorko** [comment]
@aulasau Hi, you can find demo assignments in English here https://github.com/Yorko/mlcourse.ai/tree/main/jupyter_english/assignments_demo 

But the preferred way is to follow the main site https://mlcourse.ai/book/index.html 
Assignments can be downloaded from there 
<img src="https://habrastorage.org/webt/sg/2p/ra/sg2prarvz3p6b_uctvlgoyx1m44.png" width=70%/>

French version is here https://github.com/Yorko/mlcourse.ai/tree/main/jupyter_french/assignments_demo not supported, that was a one-time activity.

**Comment by Yorko** [comment]
Hope this helps

**Comment by aulasau** [comment]
Yes, I've already found them. It was a misunderstanding: the first two topics have practice notebooks with the Titanic dataset. So I thought these notebooks were assignments. But that's not the case, so I need to get back to the real assignments.
Thx for your help!
