### ISSUE TITLE
Latex math displays incorrectly in topic-4

### ISSUE THREAD

**Issue by aulasau** [Yorko/mlcourse.ai#712]
[First arcticle](https://mlcourse.ai/book/topic04/topic4_linear_models_part1_mse_likelihood_bias_variance.html) in the topic4 does not show some math. Math under toggle button with "Small CheatSheet on matrix derivatives" looks like this:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/17138883/188671293-ba1dbe47-c5e6-491b-9191-3e48847dac09.png">

**Comment by Yorko** [comment]
Thanks @aulasau !
