### ISSUE TITLE
Typo in jupyter_russian/topic5

### ISSUE THREAD

**Issue by aulasau** [Yorko/mlcourse.ai#716]
There is a typo mistake In [bagging notebook](https://github.com/Yorko/mlcourse.ai/blob/main/jupyter_russian/topic05_bagging_rf/topic5_part1_bagging.ipynb), at the beginning with a probability value.
In the [Habr article](https://habr.com/ru/company/ods/blog/324402/) and English version of the course everything is fine.
Here, it should be "p > 0.5":
<img width="893" alt="image" src="https://user-images.githubusercontent.com/17138883/189514443-262197ce-e036-4ba0-8fe6-d5ddf98be847.png">

**Comment by aulasau** [comment]
And in the same notebook. : 
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/17138883/189514986-20f786df-b6d9-4be2-b74a-b5f5f404acf4.png">

**Comment by Yorko** [comment]
Thanks, fixed. Although notebooks in Russian are not maintained anymore.

**Comment by aulasau** [comment]
So, for Russian notebooks, is it better not to write about errors at all?

**Comment by Yorko** [comment]
Well, if you spot typos like this, you can open an issue, I'll probably be fixing them in a batch mode, i.e. not instantaneously. But in general, it's too much work to maintain the course material in 2 versions, so I won't be doing major changes (e.g. creating its Jupyter-book version or fixing the code for some deprecated library) for the Russian version of the course.
