### ISSUE TITLE
Bad view in Feature importance

### ISSUE THREAD

**Issue by aulasau** [Yorko/mlcourse.ai#718]
In the [feature importance article](https://mlcourse.ai/book/topic05/topic5_part3_feature_importance.html) there is some problem with the representation of sklearn Impurity Reduction algo. It seems like some indentations are not shown properly. 
Actually, in [English ntbk](https://github.com/Yorko/mlcourse.ai/blob/main/jupyter_english/topic05_ensembles_random_forests/topic5_part3_feature_importance.ipynb) it looks right.
![image](https://user-images.githubusercontent.com/17138883/189632320-ff9b8303-2891-42d1-92d0-b76cc06b9ede.png)

**Comment by Yorko** [comment]
Thanks a lot for attentive proof-reading, fixed in #722
