### ISSUE TITLE
Typo in the feature naming in Reduction Impurity counting

### ISSUE THREAD

**Issue by aulasau** [Yorko/mlcourse.ai#719]
In the book, [Feature importance page](https://mlcourse.ai/book/topic05/topic5_part3_feature_importance.html) there is a typo in the feature name. One of the chosen should be "Petal length (cm)".
<img width="767" alt="image" src="https://user-images.githubusercontent.com/17138883/189652317-d999f0a6-43bc-4b74-99c7-a3b0ba1a117d.png">

**Comment by Yorko** [comment]
Thanks! Fixed in #722
