### ISSUE TITLE
Data for assignment 4

### ISSUE THREAD

**Issue by jonkracht** [Yorko/mlcourse.ai#720]
Thanks for the course.  I've been working my way through it via cloning the repo off of Github.  I can't seem to find the data set for assignment 4 on sarcasm detection.  If it is indeed included, apologies; if not, how would you suggest to get it?  Via Kaggle or some other means?  Thanks again.

**Comment by aulasau** [comment]
You can find it here, at the [Kaggle competition page](https://www.kaggle.com/datasets/danofer/sarcasm)
