### ISSUE TITLE
Incredibly large output in Feature selection

### ISSUE THREAD

**Issue by aulasau** [Yorko/mlcourse.ai#721]
In the [topic 6](https://mlcourse.ai/book/topic06/topic6_feature_engineering_feature_selection.html) the output of the reverse_geocoder cell:
```python
import reverse_geocoder as revgc

revgc.search(list(zip(df.latitude, df.longitude)))
``` 
shows very huge useless output, like ~70% of the full page length. Can you cut it off? It's hard to scroll so much and I can't find any reason for it to be shown.

**Comment by Yorko** [comment]
Thanks! Fixed in #722
